// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_tokens.sql

package sqlcgen

import (
	"context"
)

const createAgentToken = `-- name: CreateAgentToken :one
INSERT INTO agent_tokens (id, name, kind, token_hash, token_prefix, refresh_token_hash, oauth_client_id, scope, expires_at, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, kind, token_hash, token_prefix, refresh_token_hash, oauth_client_id, scope, expires_at, last_used_at, created_at, revoked_at
`

type CreateAgentTokenParams struct {
	ID               string  `json:"id"`
	Name             string  `json:"name"`
	Kind             string  `json:"kind"`
	TokenHash        string  `json:"token_hash"`
	TokenPrefix      string  `json:"token_prefix"`
	RefreshTokenHash *string `json:"refresh_token_hash"`
	OauthClientID    *string `json:"oauth_client_id"`
	Scope            string  `json:"scope"`
	ExpiresAt        *int64  `json:"expires_at"`
	CreatedAt        int64   `json:"created_at"`
}

func (q *Queries) CreateAgentToken(ctx context.Context, arg CreateAgentTokenParams) (AgentToken, error) {
	row := q.db.QueryRowContext(ctx, createAgentToken,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.RefreshTokenHash,
		arg.OauthClientID,
		arg.Scope,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i AgentToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.RefreshTokenHash,
		&i.OauthClientID,
		&i.Scope,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const deleteAgentToken = `-- name: DeleteAgentToken :execrows
DELETE FROM agent_tokens WHERE id = ?
`

func (q *Queries) DeleteAgentToken(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAgentToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredOAuthTokens = `-- name: DeleteExpiredOAuthTokens :execrows
DELETE FROM agent_tokens WHERE kind = 'oauth' AND expires_at IS NOT NULL AND expires_at < ? AND (refresh_token_hash IS NULL OR created_at < ?)
`

type DeleteExpiredOAuthTokensParams struct {
	ExpiresAt *int64 `json:"expires_at"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) DeleteExpiredOAuthTokens(ctx context.Context, arg DeleteExpiredOAuthTokensParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredOAuthTokens, arg.ExpiresAt, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAgentToken = `-- name: GetAgentToken :one
SELECT id, name, kind, token_hash, token_prefix, refresh_token_hash, oauth_client_id, scope, expires_at, last_used_at, created_at, revoked_at FROM agent_tokens WHERE id = ?
`

func (q *Queries) GetAgentToken(ctx context.Context, id string) (AgentToken, error) {
	row := q.db.QueryRowContext(ctx, getAgentToken, id)
	var i AgentToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.RefreshTokenHash,
		&i.OauthClientID,
		&i.Scope,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAgentTokenByHash = `-- name: GetAgentTokenByHash :one
SELECT id, name, kind, token_hash, token_prefix, refresh_token_hash, oauth_client_id, scope, expires_at, last_used_at, created_at, revoked_at FROM agent_tokens WHERE token_hash = ?
`

func (q *Queries) GetAgentTokenByHash(ctx context.Context, tokenHash string) (AgentToken, error) {
	row := q.db.QueryRowContext(ctx, getAgentTokenByHash, tokenHash)
	var i AgentToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.RefreshTokenHash,
		&i.OauthClientID,
		&i.Scope,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAgentTokenByRefreshHash = `-- name: GetAgentTokenByRefreshHash :one
SELECT id, name, kind, token_hash, token_prefix, refresh_token_hash, oauth_client_id, scope, expires_at, last_used_at, created_at, revoked_at FROM agent_tokens WHERE refresh_token_hash = ?
`

func (q *Queries) GetAgentTokenByRefreshHash(ctx context.Context, refreshTokenHash *string) (AgentToken, error) {
	row := q.db.QueryRowContext(ctx, getAgentTokenByRefreshHash, refreshTokenHash)
	var i AgentToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.RefreshTokenHash,
		&i.OauthClientID,
		&i.Scope,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAgentTokens = `-- name: ListAgentTokens :many
SELECT id, name, kind, token_hash, token_prefix, refresh_token_hash, oauth_client_id, scope, expires_at, last_used_at, created_at, revoked_at FROM agent_tokens ORDER BY created_at DESC
`

func (q *Queries) ListAgentTokens(ctx context.Context) ([]AgentToken, error) {
	rows, err := q.db.QueryContext(ctx, listAgentTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentToken{}
	for rows.Next() {
		var i AgentToken
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.TokenHash,
			&i.TokenPrefix,
			&i.RefreshTokenHash,
			&i.OauthClientID,
			&i.Scope,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAgentToken = `-- name: RevokeAgentToken :execrows
UPDATE agent_tokens SET revoked_at = ? WHERE id = ? AND revoked_at IS NULL
`

type RevokeAgentTokenParams struct {
	RevokedAt *int64 `json:"revoked_at"`
	ID        string `json:"id"`
}

func (q *Queries) RevokeAgentToken(ctx context.Context, arg RevokeAgentTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeAgentToken, arg.RevokedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const rotateAgentToken = `-- name: RotateAgentToken :execrows
UPDATE agent_tokens
SET token_hash = ?, token_prefix = ?, refresh_token_hash = ?, expires_at = ?
WHERE id = ? AND refresh_token_hash = ?6 AND revoked_at IS NULL
`

type RotateAgentTokenParams struct {
	TokenHash           string  `json:"token_hash"`
	TokenPrefix         string  `json:"token_prefix"`
	RefreshTokenHash    *string `json:"refresh_token_hash"`
	ExpiresAt           *int64  `json:"expires_at"`
	ID                  string  `json:"id"`
	PreviousRefreshHash *string `json:"previous_refresh_hash"`
}

func (q *Queries) RotateAgentToken(ctx context.Context, arg RotateAgentTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, rotateAgentToken,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.RefreshTokenHash,
		arg.ExpiresAt,
		arg.ID,
		arg.PreviousRefreshHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchAgentToken = `-- name: TouchAgentToken :exec
UPDATE agent_tokens SET last_used_at = ? WHERE id = ?
`

type TouchAgentTokenParams struct {
	LastUsedAt *int64 `json:"last_used_at"`
	ID         string `json:"id"`
}

func (q *Queries) TouchAgentToken(ctx context.Context, arg TouchAgentTokenParams) error {
	_, err := q.db.ExecContext(ctx, touchAgentToken, arg.LastUsedAt, arg.ID)
	return err
}
