// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package sqlcgen

import (
	"context"
)

const countActiveAPIKeys = `-- name: CountActiveAPIKeys :one
SELECT COUNT(*) FROM api_keys WHERE revoked_at IS NULL
`

func (q *Queries) CountActiveAPIKeys(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveAPIKeys)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (id, name, key_hash, key_prefix, rate_limit_rpm, allowed_models, pinned_channel_id, timeout_seconds, priority, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, key_hash, key_prefix, rate_limit_rpm, allowed_models, pinned_channel_id, timeout_seconds, priority, request_count, last_used_at, created_at, revoked_at
`

type CreateAPIKeyParams struct {
	ID              string  `json:"id"`
	Name            string  `json:"name"`
	KeyHash         string  `json:"key_hash"`
	KeyPrefix       string  `json:"key_prefix"`
	RateLimitRpm    int64   `json:"rate_limit_rpm"`
	AllowedModels   string  `json:"allowed_models"`
	PinnedChannelID *string `json:"pinned_channel_id"`
	TimeoutSeconds  int64   `json:"timeout_seconds"`
	Priority        int64   `json:"priority"`
	CreatedAt       int64   `json:"created_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, createAPIKey,
		arg.ID,
		arg.Name,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.RateLimitRpm,
		arg.AllowedModels,
		arg.PinnedChannelID,
		arg.TimeoutSeconds,
		arg.Priority,
		arg.CreatedAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.RateLimitRpm,
		&i.AllowedModels,
		&i.PinnedChannelID,
		&i.TimeoutSeconds,
		&i.Priority,
		&i.RequestCount,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :execrows
DELETE FROM api_keys WHERE id = ?
`

func (q *Queries) DeleteAPIKey(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAPIKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAPIKey = `-- name: GetAPIKey :one
SELECT id, name, key_hash, key_prefix, rate_limit_rpm, allowed_models, pinned_channel_id, timeout_seconds, priority, request_count, last_used_at, created_at, revoked_at FROM api_keys WHERE id = ?
`

func (q *Queries) GetAPIKey(ctx context.Context, id string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKey, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.RateLimitRpm,
		&i.AllowedModels,
		&i.PinnedChannelID,
		&i.TimeoutSeconds,
		&i.Priority,
		&i.RequestCount,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, name, key_hash, key_prefix, rate_limit_rpm, allowed_models, pinned_channel_id, timeout_seconds, priority, request_count, last_used_at, created_at, revoked_at FROM api_keys WHERE key_hash = ?
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.RateLimitRpm,
		&i.AllowedModels,
		&i.PinnedChannelID,
		&i.TimeoutSeconds,
		&i.Priority,
		&i.RequestCount,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, name, key_hash, key_prefix, rate_limit_rpm, allowed_models, pinned_channel_id, timeout_seconds, priority, request_count, last_used_at, created_at, revoked_at FROM api_keys ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeys(ctx context.Context) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.RateLimitRpm,
			&i.AllowedModels,
			&i.PinnedChannelID,
			&i.TimeoutSeconds,
			&i.Priority,
			&i.RequestCount,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE api_keys SET revoked_at = ? WHERE id = ? AND revoked_at IS NULL
`

type RevokeAPIKeyParams struct {
	RevokedAt *int64 `json:"revoked_at"`
	ID        string `json:"id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeAPIKey, arg.RevokedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = ?, request_count = request_count + 1 WHERE id = ?
`

type TouchAPIKeyParams struct {
	LastUsedAt *int64 `json:"last_used_at"`
	ID         string `json:"id"`
}

func (q *Queries) TouchAPIKey(ctx context.Context, arg TouchAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, touchAPIKey, arg.LastUsedAt, arg.ID)
	return err
}

const updateAPIKey = `-- name: UpdateAPIKey :exec
UPDATE api_keys
SET name = ?, rate_limit_rpm = ?, allowed_models = ?, pinned_channel_id = ?, timeout_seconds = ?, priority = ?
WHERE id = ?
`

type UpdateAPIKeyParams struct {
	Name            string  `json:"name"`
	RateLimitRpm    int64   `json:"rate_limit_rpm"`
	AllowedModels   string  `json:"allowed_models"`
	PinnedChannelID *string `json:"pinned_channel_id"`
	TimeoutSeconds  int64   `json:"timeout_seconds"`
	Priority        int64   `json:"priority"`
	ID              string  `json:"id"`
}

func (q *Queries) UpdateAPIKey(ctx context.Context, arg UpdateAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, updateAPIKey,
		arg.Name,
		arg.RateLimitRpm,
		arg.AllowedModels,
		arg.PinnedChannelID,
		arg.TimeoutSeconds,
		arg.Priority,
		arg.ID,
	)
	return err
}
