// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package sqlcgen

import (
	"context"
)

const closeChannel = `-- name: CloseChannel :execrows
UPDATE channels SET status = 'offline', closed_at = ? WHERE id = ? AND closed_at IS NULL
`

type CloseChannelParams struct {
	ClosedAt *int64 `json:"closed_at"`
	ID       string `json:"id"`
}

func (q *Queries) CloseChannel(ctx context.Context, arg CloseChannelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, closeChannel, arg.ClosedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countChannelInFlight = `-- name: CountChannelInFlight :one
SELECT COUNT(*) FROM requests WHERE channel_id = ? AND status IN ('claimed', 'streaming')
`

func (q *Queries) CountChannelInFlight(ctx context.Context, channelID *string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChannelInFlight, channelID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countChannelsByStatus = `-- name: CountChannelsByStatus :one
SELECT COUNT(*) FROM channels WHERE status = ? AND closed_at IS NULL
`

func (q *Queries) CountChannelsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChannelsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (id, name, description, agent_token_id, status, models, concurrency, last_seen_at, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, description, agent_token_id, status, models, concurrency, served_count, failed_count, total_latency_ms, last_seen_at, created_at, closed_at
`

type CreateChannelParams struct {
	ID           string  `json:"id"`
	Name         string  `json:"name"`
	Description  string  `json:"description"`
	AgentTokenID *string `json:"agent_token_id"`
	Status       string  `json:"status"`
	Models       string  `json:"models"`
	Concurrency  int64   `json:"concurrency"`
	LastSeenAt   int64   `json:"last_seen_at"`
	CreatedAt    int64   `json:"created_at"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, createChannel,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.AgentTokenID,
		arg.Status,
		arg.Models,
		arg.Concurrency,
		arg.LastSeenAt,
		arg.CreatedAt,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AgentTokenID,
		&i.Status,
		&i.Models,
		&i.Concurrency,
		&i.ServedCount,
		&i.FailedCount,
		&i.TotalLatencyMs,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const deleteChannel = `-- name: DeleteChannel :execrows
DELETE FROM channels WHERE id = ?
`

func (q *Queries) DeleteChannel(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteChannel, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getChannel = `-- name: GetChannel :one
SELECT id, name, description, agent_token_id, status, models, concurrency, served_count, failed_count, total_latency_ms, last_seen_at, created_at, closed_at FROM channels WHERE id = ?
`

func (q *Queries) GetChannel(ctx context.Context, id string) (Channel, error) {
	row := q.db.QueryRowContext(ctx, getChannel, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AgentTokenID,
		&i.Status,
		&i.Models,
		&i.Concurrency,
		&i.ServedCount,
		&i.FailedCount,
		&i.TotalLatencyMs,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getOpenChannelByName = `-- name: GetOpenChannelByName :one
SELECT id, name, description, agent_token_id, status, models, concurrency, served_count, failed_count, total_latency_ms, last_seen_at, created_at, closed_at FROM channels WHERE name = ? AND closed_at IS NULL ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetOpenChannelByName(ctx context.Context, name string) (Channel, error) {
	row := q.db.QueryRowContext(ctx, getOpenChannelByName, name)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AgentTokenID,
		&i.Status,
		&i.Models,
		&i.Concurrency,
		&i.ServedCount,
		&i.FailedCount,
		&i.TotalLatencyMs,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const incrChannelFailed = `-- name: IncrChannelFailed :exec
UPDATE channels SET failed_count = failed_count + 1 WHERE id = ?
`

func (q *Queries) IncrChannelFailed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, incrChannelFailed, id)
	return err
}

const incrChannelServed = `-- name: IncrChannelServed :exec
UPDATE channels SET served_count = served_count + 1, total_latency_ms = total_latency_ms + ? WHERE id = ?
`

type IncrChannelServedParams struct {
	TotalLatencyMs int64  `json:"total_latency_ms"`
	ID             string `json:"id"`
}

func (q *Queries) IncrChannelServed(ctx context.Context, arg IncrChannelServedParams) error {
	_, err := q.db.ExecContext(ctx, incrChannelServed, arg.TotalLatencyMs, arg.ID)
	return err
}

const listChannels = `-- name: ListChannels :many
SELECT id, name, description, agent_token_id, status, models, concurrency, served_count, failed_count, total_latency_ms, last_seen_at, created_at, closed_at FROM channels ORDER BY (closed_at IS NULL) DESC, (status = 'online') DESC, last_seen_at DESC
`

func (q *Queries) ListChannels(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, listChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.AgentTokenID,
			&i.Status,
			&i.Models,
			&i.Concurrency,
			&i.ServedCount,
			&i.FailedCount,
			&i.TotalLatencyMs,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOnlineChannels = `-- name: ListOnlineChannels :many
SELECT id, name, description, agent_token_id, status, models, concurrency, served_count, failed_count, total_latency_ms, last_seen_at, created_at, closed_at FROM channels WHERE status = 'online' AND closed_at IS NULL ORDER BY last_seen_at DESC
`

func (q *Queries) ListOnlineChannels(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, listOnlineChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.AgentTokenID,
			&i.Status,
			&i.Models,
			&i.Concurrency,
			&i.ServedCount,
			&i.FailedCount,
			&i.TotalLatencyMs,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenChannels = `-- name: ListOpenChannels :many
SELECT id, name, description, agent_token_id, status, models, concurrency, served_count, failed_count, total_latency_ms, last_seen_at, created_at, closed_at FROM channels WHERE closed_at IS NULL ORDER BY (status = 'online') DESC, last_seen_at DESC
`

func (q *Queries) ListOpenChannels(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, listOpenChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.AgentTokenID,
			&i.Status,
			&i.Models,
			&i.Concurrency,
			&i.ServedCount,
			&i.FailedCount,
			&i.TotalLatencyMs,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleOnlineChannels = `-- name: ListStaleOnlineChannels :many
SELECT id, name, description, agent_token_id, status, models, concurrency, served_count, failed_count, total_latency_ms, last_seen_at, created_at, closed_at FROM channels WHERE status = 'online' AND closed_at IS NULL AND last_seen_at < ?
`

func (q *Queries) ListStaleOnlineChannels(ctx context.Context, lastSeenAt int64) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, listStaleOnlineChannels, lastSeenAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.AgentTokenID,
			&i.Status,
			&i.Models,
			&i.Concurrency,
			&i.ServedCount,
			&i.FailedCount,
			&i.TotalLatencyMs,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reopenChannel = `-- name: ReopenChannel :exec
UPDATE channels SET status = 'online', closed_at = NULL, last_seen_at = ?, agent_token_id = ?, models = ?, concurrency = ?, description = ? WHERE id = ?
`

type ReopenChannelParams struct {
	LastSeenAt   int64   `json:"last_seen_at"`
	AgentTokenID *string `json:"agent_token_id"`
	Models       string  `json:"models"`
	Concurrency  int64   `json:"concurrency"`
	Description  string  `json:"description"`
	ID           string  `json:"id"`
}

func (q *Queries) ReopenChannel(ctx context.Context, arg ReopenChannelParams) error {
	_, err := q.db.ExecContext(ctx, reopenChannel,
		arg.LastSeenAt,
		arg.AgentTokenID,
		arg.Models,
		arg.Concurrency,
		arg.Description,
		arg.ID,
	)
	return err
}

const setChannelStatus = `-- name: SetChannelStatus :exec
UPDATE channels SET status = ? WHERE id = ?
`

type SetChannelStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) SetChannelStatus(ctx context.Context, arg SetChannelStatusParams) error {
	_, err := q.db.ExecContext(ctx, setChannelStatus, arg.Status, arg.ID)
	return err
}

const touchChannel = `-- name: TouchChannel :exec
UPDATE channels SET last_seen_at = ?, status = 'online' WHERE id = ? AND closed_at IS NULL AND status != 'draining'
`

type TouchChannelParams struct {
	LastSeenAt int64  `json:"last_seen_at"`
	ID         string `json:"id"`
}

func (q *Queries) TouchChannel(ctx context.Context, arg TouchChannelParams) error {
	_, err := q.db.ExecContext(ctx, touchChannel, arg.LastSeenAt, arg.ID)
	return err
}

const updateChannelConfig = `-- name: UpdateChannelConfig :exec
UPDATE channels SET name = ?, description = ?, models = ?, concurrency = ? WHERE id = ?
`

type UpdateChannelConfigParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Models      string `json:"models"`
	Concurrency int64  `json:"concurrency"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateChannelConfig(ctx context.Context, arg UpdateChannelConfigParams) error {
	_, err := q.db.ExecContext(ctx, updateChannelConfig,
		arg.Name,
		arg.Description,
		arg.Models,
		arg.Concurrency,
		arg.ID,
	)
	return err
}
