// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package sqlcgen

import (
	"context"
)

const bumpConversation = `-- name: BumpConversation :exec
UPDATE conversations SET turn_count = ?, last_request_id = ?, model = ?, updated_at = ? WHERE id = ?
`

type BumpConversationParams struct {
	TurnCount     int64   `json:"turn_count"`
	LastRequestID *string `json:"last_request_id"`
	Model         string  `json:"model"`
	UpdatedAt     int64   `json:"updated_at"`
	ID            string  `json:"id"`
}

func (q *Queries) BumpConversation(ctx context.Context, arg BumpConversationParams) error {
	_, err := q.db.ExecContext(ctx, bumpConversation,
		arg.TurnCount,
		arg.LastRequestID,
		arg.Model,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const countConversations = `-- name: CountConversations :one
SELECT COUNT(*) FROM conversations
WHERE (api_key_id = ?1 OR ?1 = '')
  AND (title LIKE ?2 OR id LIKE ?2 OR ?2 = '')
`

type CountConversationsParams struct {
	ApiKeyID string `json:"api_key_id"`
	Search   string `json:"search"`
}

func (q *Queries) CountConversations(ctx context.Context, arg CountConversationsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countConversations, arg.ApiKeyID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (id, api_key_id, root_hash, title, model, turn_count, last_request_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, api_key_id, root_hash, title, model, turn_count, last_request_id, created_at, updated_at
`

type CreateConversationParams struct {
	ID            string  `json:"id"`
	ApiKeyID      string  `json:"api_key_id"`
	RootHash      string  `json:"root_hash"`
	Title         string  `json:"title"`
	Model         string  `json:"model"`
	TurnCount     int64   `json:"turn_count"`
	LastRequestID *string `json:"last_request_id"`
	CreatedAt     int64   `json:"created_at"`
	UpdatedAt     int64   `json:"updated_at"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, createConversation,
		arg.ID,
		arg.ApiKeyID,
		arg.RootHash,
		arg.Title,
		arg.Model,
		arg.TurnCount,
		arg.LastRequestID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ApiKeyID,
		&i.RootHash,
		&i.Title,
		&i.Model,
		&i.TurnCount,
		&i.LastRequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :execrows
DELETE FROM conversations WHERE id = ?
`

func (q *Queries) DeleteConversation(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteConversation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteOrphanConversations = `-- name: DeleteOrphanConversations :execrows
DELETE FROM conversations WHERE id NOT IN (SELECT DISTINCT conversation_id FROM requests WHERE conversation_id IS NOT NULL)
`

func (q *Queries) DeleteOrphanConversations(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOrphanConversations)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findConversationByRoot = `-- name: FindConversationByRoot :one
SELECT id, api_key_id, root_hash, title, model, turn_count, last_request_id, created_at, updated_at FROM conversations
WHERE api_key_id = ? AND root_hash = ? AND updated_at >= ?
ORDER BY updated_at DESC LIMIT 1
`

type FindConversationByRootParams struct {
	ApiKeyID  string `json:"api_key_id"`
	RootHash  string `json:"root_hash"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) FindConversationByRoot(ctx context.Context, arg FindConversationByRootParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, findConversationByRoot, arg.ApiKeyID, arg.RootHash, arg.UpdatedAt)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ApiKeyID,
		&i.RootHash,
		&i.Title,
		&i.Model,
		&i.TurnCount,
		&i.LastRequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, api_key_id, root_hash, title, model, turn_count, last_request_id, created_at, updated_at FROM conversations WHERE id = ?
`

func (q *Queries) GetConversation(ctx context.Context, id string) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ApiKeyID,
		&i.RootHash,
		&i.Title,
		&i.Model,
		&i.TurnCount,
		&i.LastRequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConversationRequests = `-- name: ListConversationRequests :many
SELECT id, api_key_id, channel_id, route_channel_id, conversation_id, turn_index, status, model, endpoint, stream, priority, request_body, response_body, response_text, error_message, history_hash, full_hash, next_hash, message_count, prompt_chars, prompt_tokens, completion_tokens, usage_estimated, attempts, max_attempts, client_ip, user_agent, finish_reason, created_at, claimed_at, first_token_at, completed_at, lease_expires_at, timeout_at FROM requests WHERE conversation_id = ? ORDER BY turn_index ASC, created_at ASC
`

func (q *Queries) ListConversationRequests(ctx context.Context, conversationID *string) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, listConversationRequests, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Request{}
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.ApiKeyID,
			&i.ChannelID,
			&i.RouteChannelID,
			&i.ConversationID,
			&i.TurnIndex,
			&i.Status,
			&i.Model,
			&i.Endpoint,
			&i.Stream,
			&i.Priority,
			&i.RequestBody,
			&i.ResponseBody,
			&i.ResponseText,
			&i.ErrorMessage,
			&i.HistoryHash,
			&i.FullHash,
			&i.NextHash,
			&i.MessageCount,
			&i.PromptChars,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.UsageEstimated,
			&i.Attempts,
			&i.MaxAttempts,
			&i.ClientIp,
			&i.UserAgent,
			&i.FinishReason,
			&i.CreatedAt,
			&i.ClaimedAt,
			&i.FirstTokenAt,
			&i.CompletedAt,
			&i.LeaseExpiresAt,
			&i.TimeoutAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversations = `-- name: ListConversations :many
SELECT id, api_key_id, root_hash, title, model, turn_count, last_request_id, created_at, updated_at FROM conversations
WHERE (api_key_id = ?1 OR ?1 = '')
  AND (title LIKE ?2 OR id LIKE ?2 OR ?2 = '')
ORDER BY updated_at DESC
LIMIT ?4 OFFSET ?3
`

type ListConversationsParams struct {
	ApiKeyID string `json:"api_key_id"`
	Search   string `json:"search"`
	Off      int64  `json:"off"`
	Lim      int64  `json:"lim"`
}

func (q *Queries) ListConversations(ctx context.Context, arg ListConversationsParams) ([]Conversation, error) {
	rows, err := q.db.QueryContext(ctx, listConversations,
		arg.ApiKeyID,
		arg.Search,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.ApiKeyID,
			&i.RootHash,
			&i.Title,
			&i.Model,
			&i.TurnCount,
			&i.LastRequestID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
