// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlcgen

import (
	"context"
)

const countEvents = `-- name: CountEvents :one
SELECT COUNT(*) FROM events
WHERE (kind = ?1 OR ?1 = '')
  AND (level = ?2 OR ?2 = '')
  AND (request_id = ?3 OR ?3 = '')
  AND (channel_id = ?4 OR ?4 = '')
  AND (api_key_id = ?5 OR ?5 = '')
  AND (message LIKE ?6 OR ?6 = '')
`

type CountEventsParams struct {
	Kind      string  `json:"kind"`
	Level     string  `json:"level"`
	RequestID *string `json:"request_id"`
	ChannelID *string `json:"channel_id"`
	ApiKeyID  *string `json:"api_key_id"`
	Search    string  `json:"search"`
}

func (q *Queries) CountEvents(ctx context.Context, arg CountEventsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEvents,
		arg.Kind,
		arg.Level,
		arg.RequestID,
		arg.ChannelID,
		arg.ApiKeyID,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteEventsOlderThan = `-- name: DeleteEventsOlderThan :execrows
DELETE FROM events WHERE ts < ?
`

func (q *Queries) DeleteEventsOlderThan(ctx context.Context, ts int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEventsOlderThan, ts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const distinctEventKinds = `-- name: DistinctEventKinds :many
SELECT DISTINCT kind FROM events ORDER BY kind
`

func (q *Queries) DistinctEventKinds(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, distinctEventKinds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var kind string
		if err := rows.Scan(&kind); err != nil {
			return nil, err
		}
		items = append(items, kind)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (ts, kind, level, request_id, channel_id, api_key_id, conversation_id, message, data)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEventParams struct {
	Ts             int64   `json:"ts"`
	Kind           string  `json:"kind"`
	Level          string  `json:"level"`
	RequestID      *string `json:"request_id"`
	ChannelID      *string `json:"channel_id"`
	ApiKeyID       *string `json:"api_key_id"`
	ConversationID *string `json:"conversation_id"`
	Message        string  `json:"message"`
	Data           string  `json:"data"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.Ts,
		arg.Kind,
		arg.Level,
		arg.RequestID,
		arg.ChannelID,
		arg.ApiKeyID,
		arg.ConversationID,
		arg.Message,
		arg.Data,
	)
	return err
}

const listEvents = `-- name: ListEvents :many
SELECT id, ts, kind, level, request_id, channel_id, api_key_id, conversation_id, message, data FROM events
WHERE (kind = ?1 OR ?1 = '')
  AND (level = ?2 OR ?2 = '')
  AND (request_id = ?3 OR ?3 = '')
  AND (channel_id = ?4 OR ?4 = '')
  AND (api_key_id = ?5 OR ?5 = '')
  AND (message LIKE ?6 OR ?6 = '')
ORDER BY id DESC
LIMIT ?8 OFFSET ?7
`

type ListEventsParams struct {
	Kind      string  `json:"kind"`
	Level     string  `json:"level"`
	RequestID *string `json:"request_id"`
	ChannelID *string `json:"channel_id"`
	ApiKeyID  *string `json:"api_key_id"`
	Search    string  `json:"search"`
	Off       int64   `json:"off"`
	Lim       int64   `json:"lim"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents,
		arg.Kind,
		arg.Level,
		arg.RequestID,
		arg.ChannelID,
		arg.ApiKeyID,
		arg.Search,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.Kind,
			&i.Level,
			&i.RequestID,
			&i.ChannelID,
			&i.ApiKeyID,
			&i.ConversationID,
			&i.Message,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentEvents = `-- name: ListRecentEvents :many
SELECT id, ts, kind, level, request_id, channel_id, api_key_id, conversation_id, message, data FROM events ORDER BY id DESC LIMIT ?
`

func (q *Queries) ListRecentEvents(ctx context.Context, limit int64) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listRecentEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.Kind,
			&i.Level,
			&i.RequestID,
			&i.ChannelID,
			&i.ApiKeyID,
			&i.ConversationID,
			&i.Message,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestEvents = `-- name: ListRequestEvents :many
SELECT id, ts, kind, level, request_id, channel_id, api_key_id, conversation_id, message, data FROM events WHERE request_id = ? ORDER BY id ASC
`

func (q *Queries) ListRequestEvents(ctx context.Context, requestID *string) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listRequestEvents, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.Kind,
			&i.Level,
			&i.RequestID,
			&i.ChannelID,
			&i.ApiKeyID,
			&i.ConversationID,
			&i.Message,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
