// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

type AgentToken struct {
	ID               string  `json:"id"`
	Name             string  `json:"name"`
	Kind             string  `json:"kind"`
	TokenHash        string  `json:"token_hash"`
	TokenPrefix      string  `json:"token_prefix"`
	RefreshTokenHash *string `json:"refresh_token_hash"`
	OauthClientID    *string `json:"oauth_client_id"`
	Scope            string  `json:"scope"`
	ExpiresAt        *int64  `json:"expires_at"`
	LastUsedAt       *int64  `json:"last_used_at"`
	CreatedAt        int64   `json:"created_at"`
	RevokedAt        *int64  `json:"revoked_at"`
}

type ApiKey struct {
	ID              string  `json:"id"`
	Name            string  `json:"name"`
	KeyHash         string  `json:"key_hash"`
	KeyPrefix       string  `json:"key_prefix"`
	RateLimitRpm    int64   `json:"rate_limit_rpm"`
	AllowedModels   string  `json:"allowed_models"`
	PinnedChannelID *string `json:"pinned_channel_id"`
	TimeoutSeconds  int64   `json:"timeout_seconds"`
	Priority        int64   `json:"priority"`
	RequestCount    int64   `json:"request_count"`
	LastUsedAt      *int64  `json:"last_used_at"`
	CreatedAt       int64   `json:"created_at"`
	RevokedAt       *int64  `json:"revoked_at"`
}

type Channel struct {
	ID             string  `json:"id"`
	Name           string  `json:"name"`
	Description    string  `json:"description"`
	AgentTokenID   *string `json:"agent_token_id"`
	Status         string  `json:"status"`
	Models         string  `json:"models"`
	Concurrency    int64   `json:"concurrency"`
	ServedCount    int64   `json:"served_count"`
	FailedCount    int64   `json:"failed_count"`
	TotalLatencyMs int64   `json:"total_latency_ms"`
	LastSeenAt     int64   `json:"last_seen_at"`
	CreatedAt      int64   `json:"created_at"`
	ClosedAt       *int64  `json:"closed_at"`
}

type Conversation struct {
	ID            string  `json:"id"`
	ApiKeyID      string  `json:"api_key_id"`
	RootHash      string  `json:"root_hash"`
	Title         string  `json:"title"`
	Model         string  `json:"model"`
	TurnCount     int64   `json:"turn_count"`
	LastRequestID *string `json:"last_request_id"`
	CreatedAt     int64   `json:"created_at"`
	UpdatedAt     int64   `json:"updated_at"`
}

type Event struct {
	ID             int64   `json:"id"`
	Ts             int64   `json:"ts"`
	Kind           string  `json:"kind"`
	Level          string  `json:"level"`
	RequestID      *string `json:"request_id"`
	ChannelID      *string `json:"channel_id"`
	ApiKeyID       *string `json:"api_key_id"`
	ConversationID *string `json:"conversation_id"`
	Message        string  `json:"message"`
	Data           string  `json:"data"`
}

type LoginToken struct {
	TokenHash string `json:"token_hash"`
	ExpiresAt int64  `json:"expires_at"`
	UsedAt    *int64 `json:"used_at"`
}

type OauthClient struct {
	ID                      string  `json:"id"`
	SecretHash              *string `json:"secret_hash"`
	Name                    string  `json:"name"`
	RedirectUris            string  `json:"redirect_uris"`
	GrantTypes              string  `json:"grant_types"`
	TokenEndpointAuthMethod string  `json:"token_endpoint_auth_method"`
	Metadata                string  `json:"metadata"`
	CreatedAt               int64   `json:"created_at"`
}

type OauthCode struct {
	CodeHash            string `json:"code_hash"`
	ClientID            string `json:"client_id"`
	RedirectUri         string `json:"redirect_uri"`
	CodeChallenge       string `json:"code_challenge"`
	CodeChallengeMethod string `json:"code_challenge_method"`
	Scope               string `json:"scope"`
	Resource            string `json:"resource"`
	ExpiresAt           int64  `json:"expires_at"`
	UsedAt              *int64 `json:"used_at"`
	CreatedAt           int64  `json:"created_at"`
}

type Request struct {
	ID               string  `json:"id"`
	ApiKeyID         string  `json:"api_key_id"`
	ChannelID        *string `json:"channel_id"`
	RouteChannelID   *string `json:"route_channel_id"`
	ConversationID   *string `json:"conversation_id"`
	TurnIndex        int64   `json:"turn_index"`
	Status           string  `json:"status"`
	Model            string  `json:"model"`
	Endpoint         string  `json:"endpoint"`
	Stream           bool    `json:"stream"`
	Priority         int64   `json:"priority"`
	RequestBody      string  `json:"request_body"`
	ResponseBody     *string `json:"response_body"`
	ResponseText     *string `json:"response_text"`
	ErrorMessage     *string `json:"error_message"`
	HistoryHash      string  `json:"history_hash"`
	FullHash         string  `json:"full_hash"`
	NextHash         *string `json:"next_hash"`
	MessageCount     int64   `json:"message_count"`
	PromptChars      int64   `json:"prompt_chars"`
	PromptTokens     int64   `json:"prompt_tokens"`
	CompletionTokens int64   `json:"completion_tokens"`
	UsageEstimated   bool    `json:"usage_estimated"`
	Attempts         int64   `json:"attempts"`
	MaxAttempts      int64   `json:"max_attempts"`
	ClientIp         string  `json:"client_ip"`
	UserAgent        string  `json:"user_agent"`
	FinishReason     *string `json:"finish_reason"`
	CreatedAt        int64   `json:"created_at"`
	ClaimedAt        *int64  `json:"claimed_at"`
	FirstTokenAt     *int64  `json:"first_token_at"`
	CompletedAt      *int64  `json:"completed_at"`
	LeaseExpiresAt   *int64  `json:"lease_expires_at"`
	TimeoutAt        int64   `json:"timeout_at"`
}

type Session struct {
	ID        string `json:"id"`
	CreatedAt int64  `json:"created_at"`
	ExpiresAt int64  `json:"expires_at"`
	UserAgent string `json:"user_agent"`
}

type Setting struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedAt int64  `json:"updated_at"`
}
