// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth.sql

package sqlcgen

import (
	"context"
)

const consumeOAuthCode = `-- name: ConsumeOAuthCode :execrows
UPDATE oauth_codes SET used_at = ? WHERE code_hash = ? AND used_at IS NULL AND expires_at > ?
`

type ConsumeOAuthCodeParams struct {
	UsedAt    *int64 `json:"used_at"`
	CodeHash  string `json:"code_hash"`
	ExpiresAt int64  `json:"expires_at"`
}

func (q *Queries) ConsumeOAuthCode(ctx context.Context, arg ConsumeOAuthCodeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeOAuthCode, arg.UsedAt, arg.CodeHash, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createOAuthClient = `-- name: CreateOAuthClient :one
INSERT INTO oauth_clients (id, secret_hash, name, redirect_uris, grant_types, token_endpoint_auth_method, metadata, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, secret_hash, name, redirect_uris, grant_types, token_endpoint_auth_method, metadata, created_at
`

type CreateOAuthClientParams struct {
	ID                      string  `json:"id"`
	SecretHash              *string `json:"secret_hash"`
	Name                    string  `json:"name"`
	RedirectUris            string  `json:"redirect_uris"`
	GrantTypes              string  `json:"grant_types"`
	TokenEndpointAuthMethod string  `json:"token_endpoint_auth_method"`
	Metadata                string  `json:"metadata"`
	CreatedAt               int64   `json:"created_at"`
}

func (q *Queries) CreateOAuthClient(ctx context.Context, arg CreateOAuthClientParams) (OauthClient, error) {
	row := q.db.QueryRowContext(ctx, createOAuthClient,
		arg.ID,
		arg.SecretHash,
		arg.Name,
		arg.RedirectUris,
		arg.GrantTypes,
		arg.TokenEndpointAuthMethod,
		arg.Metadata,
		arg.CreatedAt,
	)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.SecretHash,
		&i.Name,
		&i.RedirectUris,
		&i.GrantTypes,
		&i.TokenEndpointAuthMethod,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createOAuthCode = `-- name: CreateOAuthCode :exec
INSERT INTO oauth_codes (code_hash, client_id, redirect_uri, code_challenge, code_challenge_method, scope, resource, expires_at, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateOAuthCodeParams struct {
	CodeHash            string `json:"code_hash"`
	ClientID            string `json:"client_id"`
	RedirectUri         string `json:"redirect_uri"`
	CodeChallenge       string `json:"code_challenge"`
	CodeChallengeMethod string `json:"code_challenge_method"`
	Scope               string `json:"scope"`
	Resource            string `json:"resource"`
	ExpiresAt           int64  `json:"expires_at"`
	CreatedAt           int64  `json:"created_at"`
}

func (q *Queries) CreateOAuthCode(ctx context.Context, arg CreateOAuthCodeParams) error {
	_, err := q.db.ExecContext(ctx, createOAuthCode,
		arg.CodeHash,
		arg.ClientID,
		arg.RedirectUri,
		arg.CodeChallenge,
		arg.CodeChallengeMethod,
		arg.Scope,
		arg.Resource,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredOAuthCodes = `-- name: DeleteExpiredOAuthCodes :execrows
DELETE FROM oauth_codes WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredOAuthCodes(ctx context.Context, expiresAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredOAuthCodes, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteOAuthClient = `-- name: DeleteOAuthClient :execrows
DELETE FROM oauth_clients WHERE id = ?
`

func (q *Queries) DeleteOAuthClient(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOAuthClient, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getOAuthClient = `-- name: GetOAuthClient :one
SELECT id, secret_hash, name, redirect_uris, grant_types, token_endpoint_auth_method, metadata, created_at FROM oauth_clients WHERE id = ?
`

func (q *Queries) GetOAuthClient(ctx context.Context, id string) (OauthClient, error) {
	row := q.db.QueryRowContext(ctx, getOAuthClient, id)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.SecretHash,
		&i.Name,
		&i.RedirectUris,
		&i.GrantTypes,
		&i.TokenEndpointAuthMethod,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthCode = `-- name: GetOAuthCode :one
SELECT code_hash, client_id, redirect_uri, code_challenge, code_challenge_method, scope, resource, expires_at, used_at, created_at FROM oauth_codes WHERE code_hash = ?
`

func (q *Queries) GetOAuthCode(ctx context.Context, codeHash string) (OauthCode, error) {
	row := q.db.QueryRowContext(ctx, getOAuthCode, codeHash)
	var i OauthCode
	err := row.Scan(
		&i.CodeHash,
		&i.ClientID,
		&i.RedirectUri,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.Scope,
		&i.Resource,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listOAuthClients = `-- name: ListOAuthClients :many
SELECT id, secret_hash, name, redirect_uris, grant_types, token_endpoint_auth_method, metadata, created_at FROM oauth_clients ORDER BY created_at DESC
`

func (q *Queries) ListOAuthClients(ctx context.Context) ([]OauthClient, error) {
	rows, err := q.db.QueryContext(ctx, listOAuthClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthClient{}
	for rows.Next() {
		var i OauthClient
		if err := rows.Scan(
			&i.ID,
			&i.SecretHash,
			&i.Name,
			&i.RedirectUris,
			&i.GrantTypes,
			&i.TokenEndpointAuthMethod,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
