// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requests.sql

package sqlcgen

import (
	"context"
)

const cancelAllActiveRequests = `-- name: CancelAllActiveRequests :execrows
UPDATE requests SET status = 'cancelled', error_message = ?, completed_at = ?
WHERE status IN ('queued', 'claimed', 'streaming')
`

type CancelAllActiveRequestsParams struct {
	ErrorMessage *string `json:"error_message"`
	CompletedAt  *int64  `json:"completed_at"`
}

func (q *Queries) CancelAllActiveRequests(ctx context.Context, arg CancelAllActiveRequestsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelAllActiveRequests, arg.ErrorMessage, arg.CompletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const cancelRequest = `-- name: CancelRequest :execrows
UPDATE requests SET status = 'cancelled', error_message = ?, completed_at = ?
WHERE id = ? AND status IN ('queued', 'claimed', 'streaming')
`

type CancelRequestParams struct {
	ErrorMessage *string `json:"error_message"`
	CompletedAt  *int64  `json:"completed_at"`
	ID           string  `json:"id"`
}

func (q *Queries) CancelRequest(ctx context.Context, arg CancelRequestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelRequest, arg.ErrorMessage, arg.CompletedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const channelUsageSince = `-- name: ChannelUsageSince :many
SELECT
  channel_id,
  COUNT(*) AS total,
  CAST(COALESCE(SUM(CASE WHEN status = 'completed' THEN 1 ELSE 0 END), 0) AS INTEGER) AS completed,
  CAST(COALESCE(SUM(CASE WHEN status = 'failed' THEN 1 ELSE 0 END), 0) AS INTEGER) AS failed
FROM requests WHERE created_at >= ? AND channel_id IS NOT NULL
GROUP BY channel_id ORDER BY total DESC
`

type ChannelUsageSinceRow struct {
	ChannelID *string `json:"channel_id"`
	Total     int64   `json:"total"`
	Completed int64   `json:"completed"`
	Failed    int64   `json:"failed"`
}

func (q *Queries) ChannelUsageSince(ctx context.Context, createdAt int64) ([]ChannelUsageSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, channelUsageSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChannelUsageSinceRow{}
	for rows.Next() {
		var i ChannelUsageSinceRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.Total,
			&i.Completed,
			&i.Failed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimRequest = `-- name: ClaimRequest :execrows
UPDATE requests
SET status = 'claimed', channel_id = ?, claimed_at = ?, lease_expires_at = ?, attempts = attempts + 1, error_message = NULL
WHERE id = ? AND status = 'queued'
`

type ClaimRequestParams struct {
	ChannelID      *string `json:"channel_id"`
	ClaimedAt      *int64  `json:"claimed_at"`
	LeaseExpiresAt *int64  `json:"lease_expires_at"`
	ID             string  `json:"id"`
}

func (q *Queries) ClaimRequest(ctx context.Context, arg ClaimRequestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimRequest,
		arg.ChannelID,
		arg.ClaimedAt,
		arg.LeaseExpiresAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeRequest = `-- name: CompleteRequest :execrows
UPDATE requests
SET status = 'completed', response_body = ?, response_text = ?, next_hash = ?, prompt_tokens = ?, completion_tokens = ?,
    usage_estimated = ?, finish_reason = ?, completed_at = ?, first_token_at = COALESCE(first_token_at, ?)
WHERE id = ? AND channel_id = ? AND status IN ('claimed', 'streaming')
`

type CompleteRequestParams struct {
	ResponseBody     *string `json:"response_body"`
	ResponseText     *string `json:"response_text"`
	NextHash         *string `json:"next_hash"`
	PromptTokens     int64   `json:"prompt_tokens"`
	CompletionTokens int64   `json:"completion_tokens"`
	UsageEstimated   bool    `json:"usage_estimated"`
	FinishReason     *string `json:"finish_reason"`
	CompletedAt      *int64  `json:"completed_at"`
	FirstTokenAt     *int64  `json:"first_token_at"`
	ID               string  `json:"id"`
	ChannelID        *string `json:"channel_id"`
}

func (q *Queries) CompleteRequest(ctx context.Context, arg CompleteRequestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeRequest,
		arg.ResponseBody,
		arg.ResponseText,
		arg.NextHash,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.UsageEstimated,
		arg.FinishReason,
		arg.CompletedAt,
		arg.FirstTokenAt,
		arg.ID,
		arg.ChannelID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countInFlight = `-- name: CountInFlight :one
SELECT COUNT(*) FROM requests WHERE status IN ('claimed', 'streaming')
`

func (q *Queries) CountInFlight(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countInFlight)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countQueued = `-- name: CountQueued :one
SELECT COUNT(*) FROM requests WHERE status = 'queued'
`

func (q *Queries) CountQueued(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countQueued)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRequests = `-- name: CountRequests :one
SELECT COUNT(*) FROM requests
WHERE (status = ?1 OR ?1 = '')
  AND (api_key_id = ?2 OR ?2 = '')
  AND (channel_id = ?3 OR ?3 = '')
  AND (conversation_id = ?4 OR ?4 = '')
  AND (model = ?5 OR ?5 = '')
  AND (id LIKE ?6 OR response_text LIKE ?6 OR request_body LIKE ?6 OR ?6 = '')
`

type CountRequestsParams struct {
	Status         string  `json:"status"`
	ApiKeyID       string  `json:"api_key_id"`
	ChannelID      *string `json:"channel_id"`
	ConversationID *string `json:"conversation_id"`
	Model          string  `json:"model"`
	Search         string  `json:"search"`
}

func (q *Queries) CountRequests(ctx context.Context, arg CountRequestsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRequests,
		arg.Status,
		arg.ApiKeyID,
		arg.ChannelID,
		arg.ConversationID,
		arg.Model,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRequestsByStatus = `-- name: CountRequestsByStatus :one
SELECT COUNT(*) FROM requests WHERE status = ?
`

func (q *Queries) CountRequestsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRequestsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRequest = `-- name: CreateRequest :one
INSERT INTO requests (
  id, api_key_id, route_channel_id, conversation_id, turn_index, status, model, endpoint, stream, priority,
  request_body, history_hash, full_hash, message_count, prompt_chars, prompt_tokens, max_attempts,
  client_ip, user_agent, created_at, timeout_at
) VALUES (?, ?, ?, ?, ?, 'queued', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, api_key_id, channel_id, route_channel_id, conversation_id, turn_index, status, model, endpoint, stream, priority, request_body, response_body, response_text, error_message, history_hash, full_hash, next_hash, message_count, prompt_chars, prompt_tokens, completion_tokens, usage_estimated, attempts, max_attempts, client_ip, user_agent, finish_reason, created_at, claimed_at, first_token_at, completed_at, lease_expires_at, timeout_at
`

type CreateRequestParams struct {
	ID             string  `json:"id"`
	ApiKeyID       string  `json:"api_key_id"`
	RouteChannelID *string `json:"route_channel_id"`
	ConversationID *string `json:"conversation_id"`
	TurnIndex      int64   `json:"turn_index"`
	Model          string  `json:"model"`
	Endpoint       string  `json:"endpoint"`
	Stream         bool    `json:"stream"`
	Priority       int64   `json:"priority"`
	RequestBody    string  `json:"request_body"`
	HistoryHash    string  `json:"history_hash"`
	FullHash       string  `json:"full_hash"`
	MessageCount   int64   `json:"message_count"`
	PromptChars    int64   `json:"prompt_chars"`
	PromptTokens   int64   `json:"prompt_tokens"`
	MaxAttempts    int64   `json:"max_attempts"`
	ClientIp       string  `json:"client_ip"`
	UserAgent      string  `json:"user_agent"`
	CreatedAt      int64   `json:"created_at"`
	TimeoutAt      int64   `json:"timeout_at"`
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error) {
	row := q.db.QueryRowContext(ctx, createRequest,
		arg.ID,
		arg.ApiKeyID,
		arg.RouteChannelID,
		arg.ConversationID,
		arg.TurnIndex,
		arg.Model,
		arg.Endpoint,
		arg.Stream,
		arg.Priority,
		arg.RequestBody,
		arg.HistoryHash,
		arg.FullHash,
		arg.MessageCount,
		arg.PromptChars,
		arg.PromptTokens,
		arg.MaxAttempts,
		arg.ClientIp,
		arg.UserAgent,
		arg.CreatedAt,
		arg.TimeoutAt,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.ApiKeyID,
		&i.ChannelID,
		&i.RouteChannelID,
		&i.ConversationID,
		&i.TurnIndex,
		&i.Status,
		&i.Model,
		&i.Endpoint,
		&i.Stream,
		&i.Priority,
		&i.RequestBody,
		&i.ResponseBody,
		&i.ResponseText,
		&i.ErrorMessage,
		&i.HistoryHash,
		&i.FullHash,
		&i.NextHash,
		&i.MessageCount,
		&i.PromptChars,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.UsageEstimated,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ClientIp,
		&i.UserAgent,
		&i.FinishReason,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.FirstTokenAt,
		&i.CompletedAt,
		&i.LeaseExpiresAt,
		&i.TimeoutAt,
	)
	return i, err
}

const deleteFinishedRequestsOlderThan = `-- name: DeleteFinishedRequestsOlderThan :execrows
DELETE FROM requests WHERE created_at < ? AND status NOT IN ('queued', 'claimed', 'streaming')
`

func (q *Queries) DeleteFinishedRequestsOlderThan(ctx context.Context, createdAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFinishedRequestsOlderThan, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const distinctModels = `-- name: DistinctModels :many
SELECT DISTINCT model FROM requests ORDER BY model
`

func (q *Queries) DistinctModels(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, distinctModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var model string
		if err := rows.Scan(&model); err != nil {
			return nil, err
		}
		items = append(items, model)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expireRequest = `-- name: ExpireRequest :execrows
UPDATE requests SET status = 'expired', error_message = ?, completed_at = ?
WHERE id = ? AND status IN ('queued', 'claimed', 'streaming')
`

type ExpireRequestParams struct {
	ErrorMessage *string `json:"error_message"`
	CompletedAt  *int64  `json:"completed_at"`
	ID           string  `json:"id"`
}

func (q *Queries) ExpireRequest(ctx context.Context, arg ExpireRequestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, expireRequest, arg.ErrorMessage, arg.CompletedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const extendRequestLease = `-- name: ExtendRequestLease :execrows
UPDATE requests SET lease_expires_at = ? WHERE id = ? AND channel_id = ? AND status IN ('claimed', 'streaming')
`

type ExtendRequestLeaseParams struct {
	LeaseExpiresAt *int64  `json:"lease_expires_at"`
	ID             string  `json:"id"`
	ChannelID      *string `json:"channel_id"`
}

func (q *Queries) ExtendRequestLease(ctx context.Context, arg ExtendRequestLeaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, extendRequestLease, arg.LeaseExpiresAt, arg.ID, arg.ChannelID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const failRequest = `-- name: FailRequest :execrows
UPDATE requests SET status = 'failed', error_message = ?, completed_at = ?
WHERE id = ? AND status IN ('queued', 'claimed', 'streaming')
`

type FailRequestParams struct {
	ErrorMessage *string `json:"error_message"`
	CompletedAt  *int64  `json:"completed_at"`
	ID           string  `json:"id"`
}

func (q *Queries) FailRequest(ctx context.Context, arg FailRequestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failRequest, arg.ErrorMessage, arg.CompletedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findRequestByNextHash = `-- name: FindRequestByNextHash :one
SELECT id, api_key_id, channel_id, route_channel_id, conversation_id, turn_index, status, model, endpoint, stream, priority, request_body, response_body, response_text, error_message, history_hash, full_hash, next_hash, message_count, prompt_chars, prompt_tokens, completion_tokens, usage_estimated, attempts, max_attempts, client_ip, user_agent, finish_reason, created_at, claimed_at, first_token_at, completed_at, lease_expires_at, timeout_at FROM requests WHERE api_key_id = ? AND next_hash = ? ORDER BY created_at DESC LIMIT 1
`

type FindRequestByNextHashParams struct {
	ApiKeyID string  `json:"api_key_id"`
	NextHash *string `json:"next_hash"`
}

func (q *Queries) FindRequestByNextHash(ctx context.Context, arg FindRequestByNextHashParams) (Request, error) {
	row := q.db.QueryRowContext(ctx, findRequestByNextHash, arg.ApiKeyID, arg.NextHash)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.ApiKeyID,
		&i.ChannelID,
		&i.RouteChannelID,
		&i.ConversationID,
		&i.TurnIndex,
		&i.Status,
		&i.Model,
		&i.Endpoint,
		&i.Stream,
		&i.Priority,
		&i.RequestBody,
		&i.ResponseBody,
		&i.ResponseText,
		&i.ErrorMessage,
		&i.HistoryHash,
		&i.FullHash,
		&i.NextHash,
		&i.MessageCount,
		&i.PromptChars,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.UsageEstimated,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ClientIp,
		&i.UserAgent,
		&i.FinishReason,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.FirstTokenAt,
		&i.CompletedAt,
		&i.LeaseExpiresAt,
		&i.TimeoutAt,
	)
	return i, err
}

const getRequest = `-- name: GetRequest :one
SELECT id, api_key_id, channel_id, route_channel_id, conversation_id, turn_index, status, model, endpoint, stream, priority, request_body, response_body, response_text, error_message, history_hash, full_hash, next_hash, message_count, prompt_chars, prompt_tokens, completion_tokens, usage_estimated, attempts, max_attempts, client_ip, user_agent, finish_reason, created_at, claimed_at, first_token_at, completed_at, lease_expires_at, timeout_at FROM requests WHERE id = ?
`

func (q *Queries) GetRequest(ctx context.Context, id string) (Request, error) {
	row := q.db.QueryRowContext(ctx, getRequest, id)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.ApiKeyID,
		&i.ChannelID,
		&i.RouteChannelID,
		&i.ConversationID,
		&i.TurnIndex,
		&i.Status,
		&i.Model,
		&i.Endpoint,
		&i.Stream,
		&i.Priority,
		&i.RequestBody,
		&i.ResponseBody,
		&i.ResponseText,
		&i.ErrorMessage,
		&i.HistoryHash,
		&i.FullHash,
		&i.NextHash,
		&i.MessageCount,
		&i.PromptChars,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.UsageEstimated,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ClientIp,
		&i.UserAgent,
		&i.FinishReason,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.FirstTokenAt,
		&i.CompletedAt,
		&i.LeaseExpiresAt,
		&i.TimeoutAt,
	)
	return i, err
}

const keyUsageSince = `-- name: KeyUsageSince :many
SELECT
  api_key_id,
  COUNT(*) AS total,
  CAST(COALESCE(SUM(CASE WHEN status = 'completed' THEN 1 ELSE 0 END), 0) AS INTEGER) AS completed,
  CAST(COALESCE(SUM(prompt_tokens), 0) AS INTEGER) AS prompt_tokens,
  CAST(COALESCE(SUM(completion_tokens), 0) AS INTEGER) AS completion_tokens
FROM requests WHERE created_at >= ?
GROUP BY api_key_id ORDER BY total DESC
`

type KeyUsageSinceRow struct {
	ApiKeyID         string `json:"api_key_id"`
	Total            int64  `json:"total"`
	Completed        int64  `json:"completed"`
	PromptTokens     int64  `json:"prompt_tokens"`
	CompletionTokens int64  `json:"completion_tokens"`
}

func (q *Queries) KeyUsageSince(ctx context.Context, createdAt int64) ([]KeyUsageSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, keyUsageSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KeyUsageSinceRow{}
	for rows.Next() {
		var i KeyUsageSinceRow
		if err := rows.Scan(
			&i.ApiKeyID,
			&i.Total,
			&i.Completed,
			&i.PromptTokens,
			&i.CompletionTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latencySamplesSince = `-- name: LatencySamplesSince :many
SELECT
  CAST(completed_at - created_at AS INTEGER) AS latency_ms,
  CAST(COALESCE(first_token_at, completed_at) - created_at AS INTEGER) AS ttft_ms,
  CAST(COALESCE(claimed_at, created_at) - created_at AS INTEGER) AS queue_ms
FROM requests
WHERE status = 'completed' AND completed_at IS NOT NULL AND created_at >= ?
ORDER BY created_at DESC LIMIT 5000
`

type LatencySamplesSinceRow struct {
	LatencyMs int64 `json:"latency_ms"`
	TtftMs    int64 `json:"ttft_ms"`
	QueueMs   int64 `json:"queue_ms"`
}

func (q *Queries) LatencySamplesSince(ctx context.Context, createdAt int64) ([]LatencySamplesSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, latencySamplesSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatencySamplesSinceRow{}
	for rows.Next() {
		var i LatencySamplesSinceRow
		if err := rows.Scan(&i.LatencyMs, &i.TtftMs, &i.QueueMs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveRequests = `-- name: ListActiveRequests :many
SELECT id, api_key_id, channel_id, route_channel_id, conversation_id, turn_index, status, model, endpoint, stream, priority, request_body, response_body, response_text, error_message, history_hash, full_hash, next_hash, message_count, prompt_chars, prompt_tokens, completion_tokens, usage_estimated, attempts, max_attempts, client_ip, user_agent, finish_reason, created_at, claimed_at, first_token_at, completed_at, lease_expires_at, timeout_at FROM requests WHERE status IN ('queued', 'claimed', 'streaming') ORDER BY created_at ASC
`

func (q *Queries) ListActiveRequests(ctx context.Context) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, listActiveRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Request{}
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.ApiKeyID,
			&i.ChannelID,
			&i.RouteChannelID,
			&i.ConversationID,
			&i.TurnIndex,
			&i.Status,
			&i.Model,
			&i.Endpoint,
			&i.Stream,
			&i.Priority,
			&i.RequestBody,
			&i.ResponseBody,
			&i.ResponseText,
			&i.ErrorMessage,
			&i.HistoryHash,
			&i.FullHash,
			&i.NextHash,
			&i.MessageCount,
			&i.PromptChars,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.UsageEstimated,
			&i.Attempts,
			&i.MaxAttempts,
			&i.ClientIp,
			&i.UserAgent,
			&i.FinishReason,
			&i.CreatedAt,
			&i.ClaimedAt,
			&i.FirstTokenAt,
			&i.CompletedAt,
			&i.LeaseExpiresAt,
			&i.TimeoutAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClaimableRequests = `-- name: ListClaimableRequests :many
SELECT id, api_key_id, channel_id, route_channel_id, conversation_id, turn_index, status, model, endpoint, stream, priority, request_body, response_body, response_text, error_message, history_hash, full_hash, next_hash, message_count, prompt_chars, prompt_tokens, completion_tokens, usage_estimated, attempts, max_attempts, client_ip, user_agent, finish_reason, created_at, claimed_at, first_token_at, completed_at, lease_expires_at, timeout_at FROM requests
WHERE status = 'queued'
  AND timeout_at > ?1
  AND (route_channel_id IS NULL OR route_channel_id = ?2)
ORDER BY priority DESC, created_at ASC
LIMIT 50
`

type ListClaimableRequestsParams struct {
	Now       int64   `json:"now"`
	ChannelID *string `json:"channel_id"`
}

func (q *Queries) ListClaimableRequests(ctx context.Context, arg ListClaimableRequestsParams) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, listClaimableRequests, arg.Now, arg.ChannelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Request{}
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.ApiKeyID,
			&i.ChannelID,
			&i.RouteChannelID,
			&i.ConversationID,
			&i.TurnIndex,
			&i.Status,
			&i.Model,
			&i.Endpoint,
			&i.Stream,
			&i.Priority,
			&i.RequestBody,
			&i.ResponseBody,
			&i.ResponseText,
			&i.ErrorMessage,
			&i.HistoryHash,
			&i.FullHash,
			&i.NextHash,
			&i.MessageCount,
			&i.PromptChars,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.UsageEstimated,
			&i.Attempts,
			&i.MaxAttempts,
			&i.ClientIp,
			&i.UserAgent,
			&i.FinishReason,
			&i.CreatedAt,
			&i.ClaimedAt,
			&i.FirstTokenAt,
			&i.CompletedAt,
			&i.LeaseExpiresAt,
			&i.TimeoutAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredLeases = `-- name: ListExpiredLeases :many
SELECT id, api_key_id, channel_id, route_channel_id, conversation_id, turn_index, status, model, endpoint, stream, priority, request_body, response_body, response_text, error_message, history_hash, full_hash, next_hash, message_count, prompt_chars, prompt_tokens, completion_tokens, usage_estimated, attempts, max_attempts, client_ip, user_agent, finish_reason, created_at, claimed_at, first_token_at, completed_at, lease_expires_at, timeout_at FROM requests WHERE status IN ('claimed', 'streaming') AND lease_expires_at IS NOT NULL AND lease_expires_at < ?
`

func (q *Queries) ListExpiredLeases(ctx context.Context, leaseExpiresAt *int64) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredLeases, leaseExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Request{}
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.ApiKeyID,
			&i.ChannelID,
			&i.RouteChannelID,
			&i.ConversationID,
			&i.TurnIndex,
			&i.Status,
			&i.Model,
			&i.Endpoint,
			&i.Stream,
			&i.Priority,
			&i.RequestBody,
			&i.ResponseBody,
			&i.ResponseText,
			&i.ErrorMessage,
			&i.HistoryHash,
			&i.FullHash,
			&i.NextHash,
			&i.MessageCount,
			&i.PromptChars,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.UsageEstimated,
			&i.Attempts,
			&i.MaxAttempts,
			&i.ClientIp,
			&i.UserAgent,
			&i.FinishReason,
			&i.CreatedAt,
			&i.ClaimedAt,
			&i.FirstTokenAt,
			&i.CompletedAt,
			&i.LeaseExpiresAt,
			&i.TimeoutAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInFlightForChannel = `-- name: ListInFlightForChannel :many
SELECT id, api_key_id, channel_id, route_channel_id, conversation_id, turn_index, status, model, endpoint, stream, priority, request_body, response_body, response_text, error_message, history_hash, full_hash, next_hash, message_count, prompt_chars, prompt_tokens, completion_tokens, usage_estimated, attempts, max_attempts, client_ip, user_agent, finish_reason, created_at, claimed_at, first_token_at, completed_at, lease_expires_at, timeout_at FROM requests WHERE channel_id = ? AND status IN ('claimed', 'streaming')
`

func (q *Queries) ListInFlightForChannel(ctx context.Context, channelID *string) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, listInFlightForChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Request{}
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.ApiKeyID,
			&i.ChannelID,
			&i.RouteChannelID,
			&i.ConversationID,
			&i.TurnIndex,
			&i.Status,
			&i.Model,
			&i.Endpoint,
			&i.Stream,
			&i.Priority,
			&i.RequestBody,
			&i.ResponseBody,
			&i.ResponseText,
			&i.ErrorMessage,
			&i.HistoryHash,
			&i.FullHash,
			&i.NextHash,
			&i.MessageCount,
			&i.PromptChars,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.UsageEstimated,
			&i.Attempts,
			&i.MaxAttempts,
			&i.ClientIp,
			&i.UserAgent,
			&i.FinishReason,
			&i.CreatedAt,
			&i.ClaimedAt,
			&i.FirstTokenAt,
			&i.CompletedAt,
			&i.LeaseExpiresAt,
			&i.TimeoutAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentRequests = `-- name: ListRecentRequests :many
SELECT id, api_key_id, channel_id, route_channel_id, conversation_id, turn_index, status, model, endpoint, stream, priority, request_body, response_body, response_text, error_message, history_hash, full_hash, next_hash, message_count, prompt_chars, prompt_tokens, completion_tokens, usage_estimated, attempts, max_attempts, client_ip, user_agent, finish_reason, created_at, claimed_at, first_token_at, completed_at, lease_expires_at, timeout_at FROM requests ORDER BY created_at DESC LIMIT ?
`

func (q *Queries) ListRecentRequests(ctx context.Context, limit int64) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, listRecentRequests, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Request{}
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.ApiKeyID,
			&i.ChannelID,
			&i.RouteChannelID,
			&i.ConversationID,
			&i.TurnIndex,
			&i.Status,
			&i.Model,
			&i.Endpoint,
			&i.Stream,
			&i.Priority,
			&i.RequestBody,
			&i.ResponseBody,
			&i.ResponseText,
			&i.ErrorMessage,
			&i.HistoryHash,
			&i.FullHash,
			&i.NextHash,
			&i.MessageCount,
			&i.PromptChars,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.UsageEstimated,
			&i.Attempts,
			&i.MaxAttempts,
			&i.ClientIp,
			&i.UserAgent,
			&i.FinishReason,
			&i.CreatedAt,
			&i.ClaimedAt,
			&i.FirstTokenAt,
			&i.CompletedAt,
			&i.LeaseExpiresAt,
			&i.TimeoutAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequests = `-- name: ListRequests :many
SELECT id, api_key_id, channel_id, route_channel_id, conversation_id, turn_index, status, model, endpoint, stream, priority, request_body, response_body, response_text, error_message, history_hash, full_hash, next_hash, message_count, prompt_chars, prompt_tokens, completion_tokens, usage_estimated, attempts, max_attempts, client_ip, user_agent, finish_reason, created_at, claimed_at, first_token_at, completed_at, lease_expires_at, timeout_at FROM requests
WHERE (status = ?1 OR ?1 = '')
  AND (api_key_id = ?2 OR ?2 = '')
  AND (channel_id = ?3 OR ?3 = '')
  AND (conversation_id = ?4 OR ?4 = '')
  AND (model = ?5 OR ?5 = '')
  AND (id LIKE ?6 OR response_text LIKE ?6 OR request_body LIKE ?6 OR ?6 = '')
ORDER BY created_at DESC
LIMIT ?8 OFFSET ?7
`

type ListRequestsParams struct {
	Status         string  `json:"status"`
	ApiKeyID       string  `json:"api_key_id"`
	ChannelID      *string `json:"channel_id"`
	ConversationID *string `json:"conversation_id"`
	Model          string  `json:"model"`
	Search         string  `json:"search"`
	Off            int64   `json:"off"`
	Lim            int64   `json:"lim"`
}

func (q *Queries) ListRequests(ctx context.Context, arg ListRequestsParams) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, listRequests,
		arg.Status,
		arg.ApiKeyID,
		arg.ChannelID,
		arg.ConversationID,
		arg.Model,
		arg.Search,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Request{}
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.ApiKeyID,
			&i.ChannelID,
			&i.RouteChannelID,
			&i.ConversationID,
			&i.TurnIndex,
			&i.Status,
			&i.Model,
			&i.Endpoint,
			&i.Stream,
			&i.Priority,
			&i.RequestBody,
			&i.ResponseBody,
			&i.ResponseText,
			&i.ErrorMessage,
			&i.HistoryHash,
			&i.FullHash,
			&i.NextHash,
			&i.MessageCount,
			&i.PromptChars,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.UsageEstimated,
			&i.Attempts,
			&i.MaxAttempts,
			&i.ClientIp,
			&i.UserAgent,
			&i.FinishReason,
			&i.CreatedAt,
			&i.ClaimedAt,
			&i.FirstTokenAt,
			&i.CompletedAt,
			&i.LeaseExpiresAt,
			&i.TimeoutAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimedOutRequests = `-- name: ListTimedOutRequests :many
SELECT id, api_key_id, channel_id, route_channel_id, conversation_id, turn_index, status, model, endpoint, stream, priority, request_body, response_body, response_text, error_message, history_hash, full_hash, next_hash, message_count, prompt_chars, prompt_tokens, completion_tokens, usage_estimated, attempts, max_attempts, client_ip, user_agent, finish_reason, created_at, claimed_at, first_token_at, completed_at, lease_expires_at, timeout_at FROM requests WHERE status IN ('queued', 'claimed', 'streaming') AND timeout_at < ?
`

func (q *Queries) ListTimedOutRequests(ctx context.Context, timeoutAt int64) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, listTimedOutRequests, timeoutAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Request{}
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.ApiKeyID,
			&i.ChannelID,
			&i.RouteChannelID,
			&i.ConversationID,
			&i.TurnIndex,
			&i.Status,
			&i.Model,
			&i.Endpoint,
			&i.Stream,
			&i.Priority,
			&i.RequestBody,
			&i.ResponseBody,
			&i.ResponseText,
			&i.ErrorMessage,
			&i.HistoryHash,
			&i.FullHash,
			&i.NextHash,
			&i.MessageCount,
			&i.PromptChars,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.UsageEstimated,
			&i.Attempts,
			&i.MaxAttempts,
			&i.ClientIp,
			&i.UserAgent,
			&i.FinishReason,
			&i.CreatedAt,
			&i.ClaimedAt,
			&i.FirstTokenAt,
			&i.CompletedAt,
			&i.LeaseExpiresAt,
			&i.TimeoutAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRequestStreaming = `-- name: MarkRequestStreaming :execrows
UPDATE requests
SET status = 'streaming', first_token_at = COALESCE(first_token_at, ?), lease_expires_at = ?
WHERE id = ? AND channel_id = ? AND status IN ('claimed', 'streaming')
`

type MarkRequestStreamingParams struct {
	FirstTokenAt   *int64  `json:"first_token_at"`
	LeaseExpiresAt *int64  `json:"lease_expires_at"`
	ID             string  `json:"id"`
	ChannelID      *string `json:"channel_id"`
}

func (q *Queries) MarkRequestStreaming(ctx context.Context, arg MarkRequestStreamingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markRequestStreaming,
		arg.FirstTokenAt,
		arg.LeaseExpiresAt,
		arg.ID,
		arg.ChannelID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const modelUsageSince = `-- name: ModelUsageSince :many
SELECT
  model,
  COUNT(*) AS total,
  CAST(COALESCE(SUM(prompt_tokens), 0) AS INTEGER) AS prompt_tokens,
  CAST(COALESCE(SUM(completion_tokens), 0) AS INTEGER) AS completion_tokens
FROM requests WHERE created_at >= ?
GROUP BY model ORDER BY total DESC LIMIT 20
`

type ModelUsageSinceRow struct {
	Model            string `json:"model"`
	Total            int64  `json:"total"`
	PromptTokens     int64  `json:"prompt_tokens"`
	CompletionTokens int64  `json:"completion_tokens"`
}

func (q *Queries) ModelUsageSince(ctx context.Context, createdAt int64) ([]ModelUsageSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, modelUsageSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModelUsageSinceRow{}
	for rows.Next() {
		var i ModelUsageSinceRow
		if err := rows.Scan(
			&i.Model,
			&i.Total,
			&i.PromptTokens,
			&i.CompletionTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requestStatsSince = `-- name: RequestStatsSince :one
SELECT
  COUNT(*) AS total,
  CAST(COALESCE(SUM(CASE WHEN status = 'completed' THEN 1 ELSE 0 END), 0) AS INTEGER) AS completed,
  CAST(COALESCE(SUM(CASE WHEN status = 'failed' THEN 1 ELSE 0 END), 0) AS INTEGER) AS failed,
  CAST(COALESCE(SUM(CASE WHEN status IN ('cancelled', 'expired') THEN 1 ELSE 0 END), 0) AS INTEGER) AS dropped,
  CAST(COALESCE(SUM(prompt_tokens), 0) AS INTEGER) AS prompt_tokens,
  CAST(COALESCE(SUM(completion_tokens), 0) AS INTEGER) AS completion_tokens
FROM requests WHERE created_at >= ?
`

type RequestStatsSinceRow struct {
	Total            int64 `json:"total"`
	Completed        int64 `json:"completed"`
	Failed           int64 `json:"failed"`
	Dropped          int64 `json:"dropped"`
	PromptTokens     int64 `json:"prompt_tokens"`
	CompletionTokens int64 `json:"completion_tokens"`
}

func (q *Queries) RequestStatsSince(ctx context.Context, createdAt int64) (RequestStatsSinceRow, error) {
	row := q.db.QueryRowContext(ctx, requestStatsSince, createdAt)
	var i RequestStatsSinceRow
	err := row.Scan(
		&i.Total,
		&i.Completed,
		&i.Failed,
		&i.Dropped,
		&i.PromptTokens,
		&i.CompletionTokens,
	)
	return i, err
}

const requeueRequest = `-- name: RequeueRequest :execrows
UPDATE requests
SET status = 'queued', channel_id = NULL, claimed_at = NULL, lease_expires_at = NULL, first_token_at = NULL, error_message = ?
WHERE id = ? AND status IN ('claimed', 'streaming')
`

type RequeueRequestParams struct {
	ErrorMessage *string `json:"error_message"`
	ID           string  `json:"id"`
}

func (q *Queries) RequeueRequest(ctx context.Context, arg RequeueRequestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, requeueRequest, arg.ErrorMessage, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const throughputBuckets = `-- name: ThroughputBuckets :many
SELECT
  CAST(created_at / ?1 AS INTEGER) AS bucket,
  COUNT(*) AS total,
  CAST(COALESCE(SUM(CASE WHEN status = 'completed' THEN 1 ELSE 0 END), 0) AS INTEGER) AS completed,
  CAST(COALESCE(SUM(CASE WHEN status IN ('failed', 'cancelled', 'expired') THEN 1 ELSE 0 END), 0) AS INTEGER) AS failed
FROM requests
WHERE created_at >= ?2
GROUP BY bucket ORDER BY bucket
`

type ThroughputBucketsParams struct {
	BucketMs int64 `json:"bucket_ms"`
	Since    int64 `json:"since"`
}

type ThroughputBucketsRow struct {
	Bucket    int64 `json:"bucket"`
	Total     int64 `json:"total"`
	Completed int64 `json:"completed"`
	Failed    int64 `json:"failed"`
}

func (q *Queries) ThroughputBuckets(ctx context.Context, arg ThroughputBucketsParams) ([]ThroughputBucketsRow, error) {
	rows, err := q.db.QueryContext(ctx, throughputBuckets, arg.BucketMs, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ThroughputBucketsRow{}
	for rows.Next() {
		var i ThroughputBucketsRow
		if err := rows.Scan(
			&i.Bucket,
			&i.Total,
			&i.Completed,
			&i.Failed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
