// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlcgen

import (
	"context"
)

const consumeLoginToken = `-- name: ConsumeLoginToken :execrows
UPDATE login_tokens SET used_at = ? WHERE token_hash = ? AND used_at IS NULL AND expires_at > ?
`

type ConsumeLoginTokenParams struct {
	UsedAt    *int64 `json:"used_at"`
	TokenHash string `json:"token_hash"`
	ExpiresAt int64  `json:"expires_at"`
}

func (q *Queries) ConsumeLoginToken(ctx context.Context, arg ConsumeLoginTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeLoginToken, arg.UsedAt, arg.TokenHash, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createLoginToken = `-- name: CreateLoginToken :exec
INSERT INTO login_tokens (token_hash, expires_at) VALUES (?, ?)
`

type CreateLoginTokenParams struct {
	TokenHash string `json:"token_hash"`
	ExpiresAt int64  `json:"expires_at"`
}

func (q *Queries) CreateLoginToken(ctx context.Context, arg CreateLoginTokenParams) error {
	_, err := q.db.ExecContext(ctx, createLoginToken, arg.TokenHash, arg.ExpiresAt)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, created_at, expires_at, user_agent) VALUES (?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID        string `json:"id"`
	CreatedAt int64  `json:"created_at"`
	ExpiresAt int64  `json:"expires_at"`
	UserAgent string `json:"user_agent"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.UserAgent,
	)
	return err
}

const deleteAllSessions = `-- name: DeleteAllSessions :execrows
DELETE FROM sessions
`

func (q *Queries) DeleteAllSessions(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAllSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredLoginTokens = `-- name: DeleteExpiredLoginTokens :execrows
DELETE FROM login_tokens WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredLoginTokens(ctx context.Context, expiresAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredLoginTokens, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, created_at, expires_at, user_agent FROM sessions WHERE id = ? AND expires_at > ?
`

type GetSessionParams struct {
	ID        string `json:"id"`
	ExpiresAt int64  `json:"expires_at"`
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, arg.ID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UserAgent,
	)
	return i, err
}
